apiVersion: v1
kind: Service
metadata:
  name: juice-shop-service
spec:
  type: NodePort
  selector:
    app: juice-shop
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30001
