---
- name: Deploy OWASP Juice Shop
  hosts: localhost
  become: yes
  vars:
    app_namespace: juice-shop-namespace 
    node_ip: "{{ lookup('pipe', 'kubectl get nodes -o jsonpath=\"{.items[0].status.addresses[0].address}\"') }}"

  tasks:
    - name: Create namespace for Juice Shop
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ app_namespace }}"

    - name: Create Kubernetes Secret for JWT_SECRET
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: juice-shop-secret
            namespace: "{{ app_namespace }}"
          type: Opaque
          data:
            jwtSecret: "{{ vault_jwt_secret | b64encode }}"

    - name: Deploy Juice Shop using Helm with NodePort
      shell: |
        helm upgrade --install juice-shop /home/carrydan/juice-shop/helm-charts/juice-shop \
        --namespace "{{ app_namespace }}" \
        --set env.JWT_SECRET="{{ vault_jwt_secret }}" \
        --set service.type=NodePort \
        --set service.nodePort=30000
      args:
        chdir: /home/carrydan/juice-shop/helm-charts/juice-shop

    - name: Wait for Juice Shop pods to be running
      shell: |
        kubectl get pods -n "{{ app_namespace }}" -l app=juice-shop -o jsonpath='{.items[0].status.phase}'
      register: juice_shop_status
      until: juice_shop_status.stdout == "Running"
      retries: 20
      delay: 30

    - name: Display Juice Shop access URL
      debug:
        msg: |
          Access Juice Shop at: http://{{ node_ip }}:30000