---
- hosts: localhost
  become: yes
  tasks:
    # Install Kubernetes collection for Helm
    - name: Install Kubernetes collection for Helm
      ansible.builtin.command: ansible-galaxy collection install community.kubernetes
      async: 600  # Allow task to run for up to 10 minutes
      poll: 10    # Check status every 10 seconds

    # Install General collection for Helm
    - name: Install General collection for Helm
      ansible.builtin.command: ansible-galaxy collection install community.general
      async: 600  # Allow task to run for up to 10 minutes
      poll: 10    # Check status every 10 seconds

    # Install Python dependencies for Ansible
    - name: Install Python dependencies for Ansible
      ansible.builtin.shell: apt-get install -y python3-pip && pip3 install ansible
      async: 600  # Allow task to run for up to 10 minutes
      poll: 10    # Check status every 10 seconds
