---
- name: Install Monitoring Stack (Prometheus and Grafana)
  hosts: localhost
  connection: local
  gather_facts: yes

  vars:
    kubeconfig_path: "/home/carrydan/.kube/config"
    node_ip: "{{ lookup('pipe', 'kubectl get nodes -o jsonpath=\"{.items[0].status.addresses[0].address}\"') }}"

  tasks:
    - name: Create namespace for monitoring
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: monitoring

    - name: Add Helm repository for Prometheus
      kubernetes.core.helm_repository:
        name: prometheus-community
        repo_url: https://prometheus-community.github.io/helm-charts
        repo_state: present
        kubeconfig: "{{ kubeconfig_path }}"

    - name: Add Helm repository for Grafana
      kubernetes.core.helm_repository:
        name: grafana
        repo_url: https://grafana.github.io/helm-charts
        repo_state: present
        kubeconfig: "{{ kubeconfig_path }}"

    - name: Update Helm repositories
      command:
        _raw_params: "helm repo update"
        _uses_shell: true

    - name: Install Prometheus
      kubernetes.core.helm:
        kubeconfig: "{{ kubeconfig_path }}"
        release_name: prometheus
        chart_ref: prometheus-community/prometheus
        release_namespace: monitoring
        release_state: present
        release_values:
          server:
            service:
              type: NodePort
              nodePort: 30900

    - name: Install Grafana
      kubernetes.core.helm:
        kubeconfig: "{{ kubeconfig_path }}"
        release_name: grafana
        chart_ref: grafana/grafana
        release_namespace: monitoring
        release_state: present
        release_values:
          adminPassword: "admin"
          datasources:
            datasources.yaml:
              apiVersion: 1
              datasources:
                - name: "Prometheus"
                  type: "prometheus"
                  access: "proxy"
                  isDefault: true
                  url: "http://prometheus-server.monitoring.svc.cluster.local"
          service:
            type: NodePort
            nodePort: 32000

    - name: Display Grafana and Prometheus access URLs
      debug:
        msg: |
          Access Grafana at: http://{{ node_ip }}:32000
          Access Prometheus at: http://{{ node_ip }}:30900
