---
- name: Install Monitoring Stack (Prometheus and Grafana)
  hosts: localhost
  become: yes
  vars:
    prometheus_namespace: monitoring
  tasks:
    - name: Create namespace for monitoring
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ prometheus_namespace }}"

    - name: Add Helm repository for Prometheus
      kubernetes.core.helm_repository:
        name: prometheus-community
        repo_url: https://prometheus-community.github.io/helm-charts
        state: present

    - name: Add Helm repository for Grafana
      kubernetes.core.helm_repository:
        name: grafana
        repo_url: https://grafana.github.io/helm-charts
        state: present

    - name: Update Helm repositories
      command: helm repo update
      args:
        warn: false

    - name: Install Prometheus
      kubernetes.core.helm:
        name: prometheus
        chart_ref: prometheus-community/prometheus
        release_namespace: "{{ prometheus_namespace }}"
        create_namespace: false

    - name: Install Grafana
      kubernetes.core.helm:
        name: grafana
        chart_ref: grafana/grafana
        release_namespace: "{{ prometheus_namespace }}"
        create_namespace: false
        values:
          - adminPassword: 'admin'
          - service:
              type: NodePort
              nodePort: 32000
