---
- name: Install Logging Stack (Elasticsearch, Fluentd, Kibana)
  hosts: localhost
  become: yes
  vars:
    logging_namespace: logging
    kubeconfig_path: /home/carrydan/.kube/config
    node_ip: "{{ lookup('pipe', 'kubectl get nodes -o jsonpath=\"{.items[0].status.addresses[0].address}\"') }}"

  tasks:
    - name: Create namespace for logging
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ logging_namespace }}"

    - name: Add Helm repository for Elastic
      kubernetes.core.helm_repository:
        name: elastic
        repo_url: https://helm.elastic.co
        state: present

    - name: Update Helm repositories
      ansible.builtin.command: "helm repo update"

    - name: Install Elasticsearch
      kubernetes.core.helm:
        kubeconfig: "{{ kubeconfig_path }}"
        name: elasticsearch
        chart_ref: elastic/elasticsearch
        release_namespace: "{{ logging_namespace }}"
        create_namespace: false
        release_values:
          replicas: 1
          volumeClaimTemplate:
            storageClassName: standard
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 3Gi
          service:
            type: NodePort 
            nodePort: 32002  

    - name: Wait for Elasticsearch pods to be running
      shell: |
        KUBECONFIG={{ kubeconfig_path }} kubectl get pods -n "{{ logging_namespace }}" -l app=elasticsearch-master -o jsonpath='{.items[0].status.phase}'
      register: es_status
      until: es_status.stdout == "Running"
      retries: 20
      delay: 30

    - name: Install Kibana
      kubernetes.core.helm:
        kubeconfig: "{{ kubeconfig_path }}"
        name: kibana
        chart_ref: elastic/kibana
        release_namespace: "{{ logging_namespace }}"
        create_namespace: false
        release_values:
          service:
            type: NodePort
            nodePort: 32001
          env:
            ELASTICSEARCH_HOSTS: http://elasticsearch-master:9200
        timeout: "1200s"
        wait: true

    - name: Wait for Kibana pods to be running
      shell: |
        KUBECONFIG={{ kubeconfig_path }} kubectl get pods -n "{{ logging_namespace }}" -l app=kibana -o jsonpath='{.items[0].status.phase}'
      register: kibana_status
      until: kibana_status.stdout == "Running"
      retries: 20
      delay: 30

    - name: Add Helm repository for Fluent Bit
      kubernetes.core.helm_repository:
        name: fluent
        repo_url: https://fluent.github.io/helm-charts
        state: present

    - name: Install Fluent Bit
      kubernetes.core.helm:
        kubeconfig: "{{ kubeconfig_path }}"
        name: fluent-bit
        chart_ref: fluent/fluent-bit
        release_namespace: "{{ logging_namespace }}"
        create_namespace: false
        release_values:
          backend:
            type: es
            es:
              host: elasticsearch-master
              port: 9200
          serviceAccount:
            create: true

    - name: Display Elasticsearch and Kibana access URLs
      debug:
        msg: |
          Access Elasticsearch at: http://{{ node_ip }}:32002
          Access Kibana at: http://{{ node_ip }}:32001
