name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build frontend application
        run: npm run build:frontend

  build-server:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install

      - name: Build server application
        run: npm run build:server

  build-docker:
    runs-on: ubuntu-latest
    needs: [build-frontend, build-server]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t carrydan/juice-shop:${{ github.sha }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push carrydan/juice-shop:${{ github.sha }}
          docker tag carrydan/juice-shop:${{ github.sha }} carrydan/juice-shop:latest
          docker push carrydan/juice-shop:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v3
        with:
          namespace: default
          manifests: |
            kubernetes/deployment.yaml
            kubernetes/service.yaml
          images: |
            carrydan/juice-shop:${{ github.sha }}
